server:
  port: 8001

spring:
  application:
    name: demo-provider
  zipkin:
    base-url: http://127.0.0.1:8051
  sleuth:
    sampler:
      probability: 1.0 # 定义抽样比率，默认为0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters:
      - stat,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0  #Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 200 # 连接超时时间（毫秒）
    jedis: #推荐使用jedis pool不让用了
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
mybatis:
  type-aliases-package: com.cc.provider.pojo
  mapper-locations: classpath*:mapper/*.xml

#eureka:
#  instance:
#    hostname: 127.0.0.1
#    instance-id: demo-provider-8001
#    prefer-ip-address: false
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
#  client:
#    service-url:
##      defaultZone: http://test.eureka-8101.com:8101/eureka/,http://test.eureka-8102.com:8102/eureka/
#      defaultZone: http://test.eureka-8101.com:8101/eureka/