server:
  port: 8102
spring:
  application:
    name: demo-eurake
eureka:
  instance:
    hostname: test.eureka-8102.com
    instance-id: demo-eurake-8102
    prefer-ip-address: false
  server:
    enable-self-preservation: false #设置为false表示关闭保护模式
    eviction-interval-timer-in-ms: 5000 # 设置清理的间隔时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
    service-url:
      defaultZone: http://test.eureka-8101.com:8101/eureka/ #修改默认端口和访问ip
    register-with-eureka: true #设置为false表示关闭自己注册到eureka
    fetch-registry: true #设置为false表示不从eureka获取注册信息
