server:
  port: 8042
spring:
  application:
    name: demo-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息; 备注
        defaultRabbit: #表示定义的名称，用于于binding整合 备注
          type: rabbit #消息组件类型, 支持rabbitmq 和 kafka
          environment: #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
#                virtual-host: /
      bindings:
        input:
          destination: demoExchange # 表示要使用的Exchange名称定义
          group: demo-group
        #          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
        #          binder: defaultRabbit # 设置要绑定的消息服务的具体设置





eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://test.eureka-8101.com:8101/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: demo-stream-consumer  # 在信息列表时显示主机名称
    prefer-ip-address: false     # 访问的路径变为IP地址